### ISSUE TITLE
Empirical FDR

### ISSUE THREAD

**Issue by adomingues** [roland-rad-lab/Genome-scale-pan-cancer-interrogation-of-lncRNA-dependencies-using-CasRx#1]
Hi @sc13-bioinf,

first of all thank you for sharing the code for the paper - the supp files explanation is also outstanding by common publication standards.  

And using those supplmentary tables I am trying to accomplish is to select hits in a given line, which works fine using supp table 12 and fdr < 0.25 (MAGeCK), but I am seeing inconsistent results. For example `human_lncrna_fused_10388` passes this cut-off for a single cell line in supp table 12 (KP4):

```
                     Gene_ID LN18.dropFDR LN18wo.dropFDR LN229.dropFDR A549.dropFDR NCIH460.dropFDR NCIH460wo.dropFDR KP4.dropFDR MIAPACA2.dropFDR MIAPACA2wo.dropFDR
1: human_lncrna_fused_10388     0.999957        0.99701      0.997112     0.461838        0.958886          0.997969    0.030941         0.999962           0.999939
```

but is listed as "Common essential" in supp table 13, implying that it is a hit in 2-5 cell lines:

```
                     target               unified_ID  Annotated_ID cancer_related Paper_cancer validation Paper_validation            group  LN18.lfc LN229.lfc  A549.lfc NCIH460.lfc
1: human_lncrna_fused_10388 human_lncrna_fused_10388 HSALNT0162188             NO                                          Common essential -0.573585 -1.238542 -1.973526    -1.35746
    KP4.lfc MIAPACA2.lfc
1: -4.16428     -0.90735
```

Would you mind clarifying where this inconsistency originates? Since I can't figure out this, I cannot add to table 13 the individual cell lines for which a lncRNA is a hit. I believe that the empirical FDR is what is actually used to select hits in supp table 13, but please correct me if I am wrong. 

> We calculated an empirical FDR considering false positive (FP) hits as the sum of the significant lncRNA hits in the control screenings without CasRx and total hits (true positive hits (TP) + false positive hits (FP)) as the sum of the significant lncRNA hits in the correspondent condition screenings. Empirical FDR = FP/(TP + FP). For each significant hit, we calculated a gene-unified LFC.

I also looking in the repo for the code to calculate empirical FDR mentioned in the methods but couldn't find it, thus this question.

Cheers,
António

**Comment by riccardo-trozzo** [comment]
Hi Antonio,

Thank you very much for your words about our publication, reproducibility and applicability of the method are really important to us, therefore we tried to provide a clear and comprehensive supplementary material and a well annotated code.

I would like to clarify that the empirical FDR has nothing to do with the classification of the lncRNAs into core-essential, common-essential or cell line specific categories. It's a way to measure how reliable our statistical approach is. We evaluate how many lncRNAs are a hit in a context where we should not find any hit (in our case screenings performed in cell lines without the presence of the CasRx). There is no code for the calculation, just the formula that you have pasted in your mail.

We used the FDR to identify all the potentially lncRNAs vulnerabilities, but to classify them as core, common or a cell line specific vulnerabilities we used directly the LFC of each specific lncRNA gene. In the text, we call it lncRNA-specific LFC value and is the LFC value that can be found for each lncRNA hit for each particular cell line in the Supplementary Table 13. This value is the average of the two gRNAs showing more phenotype (a more drastic LFC) in each particular cell line between all the gRNAs targeting a particular lncRNA.

You have to take into consideration that we only used the gRNAs that show a phenotype in the cell lines where a particular lncRNA was identify as a hit regarding the FDR (FDR<0.25) and the value was only calculated for the lncRNA hits not for the remaining lncRNAS. 

After we performed clustering of the lncRNA hits across the different cell lines using this value (The resulting analysis is the figure 5e). In general, a lncRNA was considered a vulnerability in a particular cell line if this LFC was smaller than -1, but this can be different in certain conditions for example for lncRNA genes whose minimum LFC value wasn’t smaller than -1 in any cell line.

In the case of your example the "human_lncrna_fused_10388" as you can see in the table that you have paste this value is smallest that -1 in four cell lines, that is the reason because is considered as a common essential lncRNA vulnerability.

I hope that this email clarifies your questions!
